uint8 UP = 1
uint8 DOWN = 2
uint8 MID = 3

float64 ch_l_x
float64 ch_l_y
float64 ch_r_x
float64 ch_r_y

uint8 s_l
uint8 s_r
float64 wheel
#mouse
float64 m_x
float64 m_y
float64 m_z
bool p_l
bool p_r
#key board
bool key_w
bool key_s
bool key_a
bool key_d
bool key_shift
bool key_ctrl
bool key_q
bool key_e
bool key_r
bool key_f
bool key_g
bool key_z
bool key_x
bool key_c
bool key_v
bool key_b

time stamp
