float64 joystick_r_x
float64 joystick_r_y
float64 joystick_l_y
float64 joystick_l_x

uint8 mode_switch
uint8 MODE_C = 0
uint8 MODE_N = 1
uint8 MODE_S = 2

bool pause_button
bool custom_button_l
bool custom_button_r
float64 wheel
bool trigger

int16 mouse_x
int16 mouse_y
int16 mouse_wheel
bool mouse_left_down
bool mouse_right_down
bool mouse_mid_down

bool key_w
bool key_s
bool key_a
bool key_d
bool key_shift
bool key_ctrl
bool key_q
bool key_e
bool key_r
bool key_f
bool key_g
bool key_z
bool key_x
bool key_c
bool key_v
bool key_b