#bonus zone status
uint8 UAV_UNOCCUPIED = 0
uint8 UAV_OCCUPIED_NOT_DEAD_STICK = 1
uint8 UAV_OCCUPIED_DEAD_STICK = 2

uint8 UNOCCUPIED = 0
uint8 BEING_OCCUPIED= 1
uint8 OCCUPIED = 2

uint8 ENERGY_SWITCH_HIT_SITE_OCCUPIED = 1
uint8 ENERGY_SWITCH_SMALL_ACTIVATE = 1
uint8 ENERGY_SWITCH_BIG_ACTIVATE =1

uint8 BASE_SHIELD_WORKING = 1
uint8 BASE_SHIELD_UNWORK = 0

uint8 self_tarmac_status
uint8 self_depot_1
uint8 self_depot_2
uint8 self_depot_3
uint8 energy_switch_status
uint8 self_gate_status
uint8 self_bunker_status
uint8 self_resource_island_status
uint8 self_base_shield_status

