<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find rm_description)/urdf/common/mecanum_wheel.urdf.xacro"/>

  <!-- https://upload.wikimedia.org/wikipedia/commons/5/52/Wheelbase_and_Track.png -->
  <xacro:property name="wheel_track" value="0.500"/>
  <xacro:property name="wheel_base" value="0.475"/>
  <xacro:property name="wheel_offset_z" value="-0.036"/>
  <xacro:property name="wheel_joint_damping" value="1.0"/>
  <xacro:property name="wheel_joint_friction" value="1.0"/>

  <link name="base_link">
    <inertial>
      <mass value="10"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="1.013" ixy="1.818e-3" ixz="5.843e-2" iyy="1.516"
               iyz="3.179e-2" izz="2.208"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://rm_description/meshes/hero/base.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="DarkGrey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://rm_description/meshes/hero/base.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
  </link>

  <xacro:mecanum_wheel prefix="front_left" parent="base_link"
                       wheel_x_offset="${wheel_track/2}" wheel_y_offset="${-wheel_base/2}"
                       wheel_z_offset="${wheel_offset_z}"
                       reflect="1"/>
  <xacro:mecanum_wheel prefix="front_right" parent="base_link"
                       wheel_x_offset="${wheel_track/2}" wheel_y_offset="${wheel_base/2}"
                       wheel_z_offset="${wheel_offset_z}"
                       reflect="-1"/>
  <xacro:mecanum_wheel prefix="back_left" parent="base_link"
                       wheel_x_offset="${-wheel_track/2}" wheel_y_offset="${wheel_base/2}"
                       wheel_z_offset="${wheel_offset_z}"
                       reflect="1"/>
  <xacro:mecanum_wheel prefix="back_right" parent="base_link"
                       wheel_x_offset="${-wheel_track/2}" wheel_y_offset="${-wheel_base/2}"
                       wheel_z_offset="${wheel_offset_z}"
                       reflect="-1"/>

  <!-- Gazebo plugin for ROS Control -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/</robotNamespace>
    </plugin>
  </gazebo>

</robot>