uint8 KEY_Q = 81
uint8 KEY_W = 87
uint8 KEY_E = 69
uint8 KEY_R = 82
uint8 KEY_T = 84
uint8 KEY_Y = 89
uint8 KEY_U = 85
uint8 KEY_O = 79

uint8 KEY_A = 65
uint8 KEY_S = 83
uint8 KEY_D = 68
uint8 KEY_F = 70
uint8 KEY_G = 71
uint8 KEY_H = 72
uint8 KEY_J = 74
uint8 KEY_K = 75
uint8 KEY_L = 76

uint8 KEY_Z = 90
uint8 KEY_X = 88
uint8 KEY_C = 67
uint8 KEY_V = 86
uint8 KEY_N = 78

float32 target_position_x
float32 target_position_y
uint8 command_keyboard
uint8 target_robot_ID
uint8 cmd_source
