# This is a format job. Pre-commit has a first-party GitHub action, so we use
# that: https://github.com/pre-commit/action

name: format

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install clang-format
        run: |
          sudo apt update
          sudo apt install -y wget gnupg2
          # 添加 LLVM 的官方 APT 仓库
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt install clang-format-14 
      - uses: pre-commit/action@v3.0.0
